prowjob_namespace: prow
pod_namespace: test-pods
log_level: debug

slack_reporter_configs:
  '*':
    job_types_to_report:
      - postsubmit
      - periodic
      - batch
    job_states_to_report:
      - failure
      - error
    channel: prow-job-notifications
    report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S01E9J0G3EU> <{{.Status.URL}}|View logs>'

in_repo_config:
  enabled:
    "*": true

deck:
  spyglass:
    gcs_browser_prefix: https://gcsweb.k8s.io/gcs/
    lenses:
      - lens:
          name: metadata
        required_files:
          - started.json|finished.json
      - lens:
          config:
          name: buildlog
        required_files:
          - build-log.txt
      - lens:
          name: junit
        required_files:
          - .*/junit.*\.xml
      - lens:
          name: coverage
        required_files:
          - artifacts/filtered.cov
        optional_files:
          - artifacts/filtered.html
      - lens:
          name: podinfo
          config:
            runner_configs:
                "default":
                  pod_link_template: "https://us-south.containers.cloud.ibm.com/kubeproxy/clusters/c2mvmdid0fcfdmiub59g/service/#/pod/test-pods/{{ .Name }}?namespace=test-pods"
        required_files:
          - podinfo.json
        optional_files:
          - prowjob.json
      - lens:
          name: links
        required_files:
          - artifacts/.*\.link\.txt
  tide_update_period: 1s

plank:
  job_url_prefix_config:
    "*": https://prow.ppc64le-cloud.org/view/
  pod_pending_timeout: 15m
  pod_unscheduled_timeout: 1m
  report_templates:
    '*': >-
      [Full PR test history](https://prow.ppc64le-cloud.org/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
      [Your PR dashboard](https://prow.ppc64le-cloud.org/pr?query=is:pr+state:open+author:{{with
      index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
  default_decoration_configs:
    "*":
      timeout: 2h
      grace_period: 15s
      censor_secrets: true
      gcs_configuration:
        bucket: s3://prow-logs
        path_strategy: explicit
      s3_credentials_secret: s3-credentials
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20220503-01ebd50188
        entrypoint: gcr.io/k8s-prow/entrypoint:v20220503-01ebd50188
        initupload: gcr.io/k8s-prow/initupload:v20220503-01ebd50188
        sidecar: gcr.io/k8s-prow/sidecar:v20220503-01ebd50188
      ssh_key_secrets:
        - bot-ssh-secret

tide:
  sync_period: 2m
  queries:
    - repos:
        - IBM/raksh
      labels:
        - lgtm
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/blocked-paths
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - orgs:
        - ppc64le-cloud
        - ocp-power-automation
      labels:
        - lgtm
        - approved
      missingLabels:
        - needs-rebase
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - do-not-merge/invalid-owners-file
        - do-not-merge/non-mergeable
  squash_label: tide/merge-method-squash

decorate_all_jobs: true

presets:
# docker-in-docker preset
- labels:
    preset-dind-enabled: "true"
  env:
  - name: DOCKER_IN_DOCKER_ENABLED
    value: "true"
  volumes:
  # kubekins-e2e legacy path
  - name: docker-graph
    emptyDir: {}
  # krte (normal) path
  - name: docker-root
    emptyDir: {}
  volumeMounts:
  - name: docker-graph
    mountPath: /docker-graph
  - name: docker-root
    mountPath: /var/lib/docker
# volume mounts for kind
- labels:
    preset-kind-volume-mounts: "true"
  volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
  volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
# containerd powervs preset
- labels:
    preset-containerd-powervs: "true"
  env:
    - name: IBMCLOUD_API_KEY
      valueFrom:
        secretKeyRef:
          name: containerd-apikey
          key: apikey
  volumeMounts:
    - name: atos-ssh-volume
      readOnly: true
      mountPath: "/etc/ssh-volume"
  volumes:
    - name: atos-ssh-volume
      secret:
        secretName: atos-powervs-ssh-key
        defaultMode: 256
